#!/usr/bin/env python3
"""
Regenerate packaging/version_info.txt from utils/version.py.

Run this after bumping the version, before building:

    python packaging/make_version_info.py

Keeping the Windows version resource generated (rather than hand-edited) means
the version shown in the .exe's Properties dialog can never drift from the
version the application reports about itself -- a small thing that saves real
confusion in support ("which build are you on?").
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from utils.version import (  # noqa: E402
    APP_NAME,
    COMPANY_NAME,
    COPYRIGHT,
    __version__,
    version_tuple,
)

TEMPLATE = """# Auto-generated by packaging/make_version_info.py -- do not edit by hand.
# Regenerate after bumping utils/version.py:
#     python packaging/make_version_info.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vers},
    prodvers={vers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{app} — album, ID photo and collage software'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', '{app}'),
         StringStruct('LegalCopyright', '{copyright}'),
         StringStruct('OriginalFilename', '{app}.exe'),
         StringStruct('ProductName', '{app}'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main() -> int:
    out = ROOT / "packaging" / "version_info.txt"
    out.write_text(
        TEMPLATE.format(
            vers=version_tuple(),
            company=COMPANY_NAME,
            app=APP_NAME,
            version=__version__,
            copyright=COPYRIGHT,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {out} for version {__version__}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
