"""Initial PhotoFlow backend schema.

Creates every table the production backend needs: users, licenses,
license_activations, devices, credit_transactions, credit_reservations,
releases, refresh_tokens and audit_logs.

Notes for whoever reads this next:

* The credit tables are created here but the feature is off
  (``PHOTOFLOW_CREDITS_ENABLED=false``). Adding tables to an empty database is
  free; adding them later, against a database holding paying customers, is a
  maintenance window. The schema lands now, the behaviour arrives in Phase 4.
* Two indexes are *partial* and cannot be expressed as a UniqueConstraint:
  ``uq_license_activations_active_seat`` (one live seat per licence per device,
  while keeping deactivation history) and ``uq_credit_transactions_user_reference``
  (idempotency for payment webhooks and client retries, enforced by the database
  rather than by application code that can be refactored away).
* ``downgrade()`` drops the PostgreSQL ENUM types explicitly. Alembic's
  autogenerate does not do this, and without it a downgrade followed by an
  upgrade fails with "type user_role already exists" -- which makes the
  migration non-reproducible from an empty database, the one property it must
  have.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-10

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', postgresql.INET(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target_type_target_id', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=30), server_default='stable', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'YANKED', name='release_status'), server_default='DRAFT', nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('release_notes_url', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('installer_filename', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('minimum_supported_version', sa.String(length=50), nullable=True),
    sa.Column('critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases')),
    sa.UniqueConstraint('version', 'channel', name='uq_releases_version_channel')
    )
    op.create_index('ix_releases_channel_status_published_at', 'releases', ['channel', 'status', 'published_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), server_default='password', nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', name='user_role'), server_default='CLIENT', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'PENDING', name='user_status'), server_default='ACTIVE', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEACTIVATED', 'REVOKED', name='device_status'), server_default='ACTIVE', nullable=False),
    sa.Column('first_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_devices_user_fingerprint')
    )
    op.create_index('ix_devices_fingerprint', 'devices', ['fingerprint'], unique=False)
    op.create_index('ix_devices_user_id', 'devices', ['user_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_last4', sa.String(length=8), nullable=False),
    sa.Column('product', sa.String(length=50), server_default='photoflow', nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED', name='license_status'), server_default='PENDING', nullable=False),
    sa.Column('activation_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_licenses_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_licenses_key_hash'))
    )
    op.create_index('ix_licenses_expires_at', 'licenses', ['expires_at'], unique=False)
    op.create_index('ix_licenses_status', 'licenses', ['status'], unique=False)
    op.create_index('ix_licenses_user_id', 'licenses', ['user_id'], unique=False)
    op.create_table('credit_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMMITTED', 'RELEASED', 'EXPIRED', name='reservation_status'), server_default='OPEN', nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_credit_reservations_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_credit_reservations_license_id_licenses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_reservations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_reservations'))
    )
    op.create_index('ix_credit_reservations_open_expiry', 'credit_reservations', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_index('ix_credit_reservations_user_id_status', 'credit_reservations', ['user_id', 'status'], unique=False)
    op.create_table('license_activations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEACTIVATED', 'REVOKED', name='activation_status'), server_default='ACTIVE', nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_license_activations_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_license_activations_license_id_licenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_activations'))
    )
    op.create_index('ix_license_activations_device_id', 'license_activations', ['device_id'], unique=False)
    op.create_index('ix_license_activations_license_id_status', 'license_activations', ['license_id', 'status'], unique=False)
    op.create_index('uq_license_activations_active_seat', 'license_activations', ['license_id', 'device_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_refresh_tokens_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'ADMIN_GRANT', 'USAGE', 'REFUND', 'BONUS', 'ADJUSTMENT', 'RESERVATION', 'COMMIT', 'RELEASE', 'EXPIRY', name='credit_transaction_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_credit_transactions_license_id_licenses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], name=op.f('fk_credit_transactions_reservation_id_credit_reservations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_transactions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions'))
    )
    op.create_index('ix_credit_transactions_license_id', 'credit_transactions', ['license_id'], unique=False)
    op.create_index('ix_credit_transactions_user_id_created_at', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_credit_transactions_user_reference', 'credit_transactions', ['user_id', 'reference_id'], unique=True, postgresql_where=sa.text('reference_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_credit_transactions_user_reference', table_name='credit_transactions', postgresql_where=sa.text('reference_id IS NOT NULL'))
    op.drop_index('ix_credit_transactions_user_id_created_at', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_license_id', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_license_activations_active_seat', table_name='license_activations', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_license_activations_license_id_status', table_name='license_activations')
    op.drop_index('ix_license_activations_device_id', table_name='license_activations')
    op.drop_table('license_activations')
    op.drop_index('ix_credit_reservations_user_id_status', table_name='credit_reservations')
    op.drop_index('ix_credit_reservations_open_expiry', table_name='credit_reservations', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_table('credit_reservations')
    op.drop_index('ix_licenses_user_id', table_name='licenses')
    op.drop_index('ix_licenses_status', table_name='licenses')
    op.drop_index('ix_licenses_expires_at', table_name='licenses')
    op.drop_table('licenses')
    op.drop_index('ix_devices_user_id', table_name='devices')
    op.drop_index('ix_devices_fingerprint', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_releases_channel_status_published_at', table_name='releases')
    op.drop_table('releases')
    op.drop_index('ix_audit_logs_target_type_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')

    # Alembic does not drop enum types it implicitly created. Without this the
    # migration is not reproducible: downgrade then upgrade fails because the
    # type already exists.
    for enum_name in (
        "credit_transaction_type",
        "reservation_status",
        "activation_status",
        "device_status",
        "license_status",
        "user_status",
        "user_role",
        "release_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
